"""Per-rule accuracy from committed files only — no model call needed.

Buckets every test transition by the rule it exercises, then joins the
autopsy's miss list: accuracy = 1 - misses/rows per rule.

Outputs: breakdown.md (table), breakdown.png (chart),
examples/exhibits.jsonl (one showcase per rule + one real miss).

Run: python breakdown.py   (stdlib; matplotlib only for the chart)
"""

import json
import os
import re
from collections import Counter

from env import GRID_SIZE, _DELTAS

HERE = os.path.dirname(os.path.abspath(__file__))

_STATE_RE = re.compile(
    r"agent=\((\d+),(\d+)\); key=(held|\(\d+,\d+\)); "
    r"door=\((\d+),(\d+)\) (locked|unlocked); has_key=(true|false); "
    r"walls=\[([^\]]*)\]"
)


def parse_state(s):
    m = _STATE_RE.fullmatch(s)
    if not m:
        raise ValueError(f"unparseable state: {s}")
    ax, ay, key, dx, dy, lock, has_key, walls = m.groups()
    return {
        "agent": (int(ax), int(ay)),
        "key": None if key == "held" else tuple(int(v) for v in key[1:-1].split(",")),
        "door": (int(dx), int(dy)),
        "locked": lock == "locked",
        "has_key": has_key == "true",
        "walls": {tuple(int(v) for v in w.split(",")) for w in re.findall(r"\((\d+,\d+)\)", walls.replace(" ", ""))},
    }


def categorize(state_str, action):
    """Name the rule this (state, action) exercises; mirrors env.step's check order."""
    s = parse_state(state_str)
    if action in _DELTAS:
        ddx, ddy = _DELTAS[action]
        target = (s["agent"][0] + ddx, s["agent"][1] + ddy)
        if not (0 <= target[0] < GRID_SIZE and 0 <= target[1] < GRID_SIZE):
            return "move: blocked by edge"
        if target in s["walls"]:
            return "move: blocked by wall"
        if target == s["door"] and s["locked"]:
            return "move: blocked by locked door"
        return "move: succeeds"
    if action == "pick up":
        return "pick up: succeeds" if (not s["has_key"] and s["key"] == s["agent"]) else "pick up: no-op"
    if action == "unlock":
        adjacent = abs(s["agent"][0] - s["door"][0]) + abs(s["agent"][1] - s["door"][1]) == 1
        ok = s["has_key"] and s["locked"] and adjacent
        return "unlock: succeeds" if ok else "unlock: no-op"
    raise ValueError(f"unknown action: {action}")


ORDER = [
    "move: succeeds",
    "move: blocked by edge",
    "move: blocked by wall",
    "move: blocked by locked door",
    "pick up: succeeds",
    "pick up: no-op",
    "unlock: succeeds",
    "unlock: no-op",
]

EXPLAIN = {
    "move: succeeds": "an ordinary step onto an empty cell",
    "move: blocked by edge": "walking off the grid — nothing happens",
    "move: blocked by wall": "walking into a wall — nothing happens",
    "move: blocked by locked door": "walking into the locked door — nothing happens",
    "pick up: succeeds": "standing on the key and taking it",
    "pick up: no-op": "'pick up' anywhere else — nothing happens",
    "unlock: succeeds": "key in hand, next to the door — it opens",
    "unlock: no-op": "'unlock' without key/adjacency — nothing happens",
}


def load_jsonl(path):
    with open(os.path.join(HERE, path)) as f:
        return [json.loads(line) for line in f]


def main():
    train = load_jsonl("data/train.jsonl")
    test = load_jsonl("data/test.jsonl")
    misses = [m for m in load_jsonl("autopsy_misses.jsonl") if m["phase"] == "single"]
    missed_keys = {(m["episode"], m["step"]) for m in misses}
    miss_by_key = {(m["episode"], m["step"]): m for m in misses}

    train_counts = Counter(categorize(r["state"], r["action"]) for r in train)
    test_rows = {c: [] for c in ORDER}
    for r in test:
        test_rows[categorize(r["state"], r["action"])].append(r)

    # --- table ---
    lines = [
        "# Per-rule test accuracy (autopsy of 2026-08-29, all 3,000 single-step transitions)",
        "",
        "Generated by `python breakdown.py` from `data/*.jsonl` + `autopsy_misses.jsonl`.",
        "",
        "| Rule | What it means | Train examples | Test examples | Misses | Accuracy |",
        "|---|---|---:|---:|---:|---:|",
    ]
    for cat in ORDER:
        n_test = len(test_rows[cat])
        n_miss = sum(1 for r in test_rows[cat] if (r["episode"], r["step"]) in missed_keys)
        acc = 100.0 * (n_test - n_miss) / n_test if n_test else float("nan")
        lines.append(
            f"| {cat} | {EXPLAIN[cat]} | {train_counts[cat]:,} | {n_test:,} | {n_miss} | {acc:.2f}% |"
        )
    total_miss = len(missed_keys)
    lines += [
        f"| **all** | | **{len(train):,}** | **{len(test):,}** | **{total_miss}** | "
        f"**{100.0 * (len(test) - total_miss) / len(test):.2f}%** |",
        "",
        "Every miss sits in a single row of this table. Note it is *not* simply",
        "the rarest rule — `unlock: succeeds` is rarer (813 examples) and scores",
        "100%. Wall-blocks are where rarity meets the hardest inference: the only",
        "rule that needs coordinate arithmetic against a variable list with no",
        "textual cue (edges are fixed geometry, the door announces itself with",
        "the word 'locked', and unlock's precondition is flagged by has_key).",
    ]
    table = "\n".join(lines) + "\n"
    with open(os.path.join(HERE, "breakdown.md"), "w") as f:
        f.write(table)
    print(table)

    # --- exhibits: first test row per rule + one real miss. Any row not in
    # the miss list was predicted exactly right, so prediction == truth. ---
    exhibits = []
    for cat in ORDER:
        r = min(test_rows[cat], key=lambda r: (r["episode"], r["step"]))
        key = (r["episode"], r["step"])
        exhibits.append({
            "rule": cat,
            "explain": EXPLAIN[cat],
            "episode": r["episode"],
            "step": r["step"],
            "state": r["state"],
            "action": r["action"],
            "truth": r["next_state"],
            "model_prediction": miss_by_key[key]["pred"] if key in missed_keys else r["next_state"],
            "correct": key not in missed_keys,
        })
    m = min(misses, key=lambda m: (m["episode"], m["step"]))
    exhibits.append({
        "rule": "THE FAILURE MODE — " + categorize(m["state"], m["action"]),
        "explain": "the model's only mistake: the world said no-op, it moved through the wall anyway",
        "episode": m["episode"],
        "step": m["step"],
        "state": m["state"],
        "action": m["action"],
        "truth": m["truth"],
        "model_prediction": m["pred"],
        "correct": False,
    })
    os.makedirs(os.path.join(HERE, "examples"), exist_ok=True)
    with open(os.path.join(HERE, "examples", "exhibits.jsonl"), "w") as f:
        for e in exhibits:
            f.write(json.dumps(e) + "\n")
    print(f"wrote examples/exhibits.jsonl ({len(exhibits)} exhibits)")

    # --- chart: training exposure vs test accuracy ---
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not installed - skipped breakdown.png")
        return

    xs, ys, labels = [], [], []
    for cat in ORDER:
        n_test = len(test_rows[cat])
        n_miss = sum(1 for r in test_rows[cat] if (r["episode"], r["step"]) in missed_keys)
        xs.append(train_counts[cat])
        ys.append(100.0 * (n_test - n_miss) / n_test)
        labels.append(cat)

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.scatter(xs, ys, s=60, zorder=3)
    # stagger the labels of the 100% dots so they don't overlap
    depth = 0
    for x, y, label in zip(xs, ys, labels):
        if y < 99:
            ax.annotate(label, (x, y), textcoords="offset points",
                        xytext=(10, 6), fontsize=8, fontweight="bold")
        else:
            ax.annotate(label, (x, y), textcoords="offset points",
                        xytext=(0, -14 - 13 * depth), fontsize=8,
                        ha="center", rotation=0,
                        arrowprops=None)
            depth = (depth + 1) % 4
    ax.set_ylim(89, 101.5)
    ax.set_xscale("log")
    ax.set_xlabel("training examples of this rule (log scale)")
    ax.set_ylabel("test accuracy on this rule (%)")
    ax.set_title("All 11 misses land on one rule: move blocked by wall")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    fig.savefig(os.path.join(HERE, "breakdown.png"), dpi=150)
    print("wrote breakdown.png")


if __name__ == "__main__":
    main()
